package cfgPkg;

public class CopyWriting {
    public final static String proven[] = {
"100% money back guarantee",
"100% satisfaction",
"2 simple steps",
"24 hour service",
"a child could do it",
"a cut above",
"a must!",
"a pleasant experience",
"a winning offer",
"absolute",
"absolutely no obligation",
"accelerate",
"accommodate",
"accurately",
"acknowledgement",
"act now",
"act today!",
"added value",
"admired",
"advanced",
"affordable",
"alert",
"all new",
"all purpose",
"all you need",
"allure",
"amazing literature",
"amazing!",
"analysis",
"analysis",
"anyone can do this",
"anytime",
"anywhere",
"appealing",
"appropriate",
"approved",
"astonishment",
"astounded",
"at your fingertips",
"at your own pace",
"at your request",
"attractive",
"authentic",
"autograph",
"automated",
"automated",
"automatic",
"available",
"awesome",
"balanced price",
"bargain price",
"bargain",
"beautiful",
"before they're gone",
"believe",
"below wholesale prices",
"beneficial",
"benefits",
"best performing",
"best quality",
"best selling",
"best",
"best-selling",
"better than",
"better",
"big bonus",
"big demand",
"big",
"block buster",
"blown away",
"bonanza",
"bonus gift",
"bonus",
"booming",
"boost",
"bottom line",
"bottom line",
"brand new",
"breakthrough",
"breathtaking",
"bright",
"brilliant",
"buy direct and save",
"buy one get one free!",
"call today",
"call toll free",
"call",
"cancel anytime",
"caring",
"cash rebate",
"caution",
"challenge",
"challenging",
"change",
"classic",
"clear",
"clearance",
"collectable",
"colossal",
"commercial",
"committed",
"common sense approach",
"compatibility",
"competitive edge",
"competitive edge",
"complete facts",
"complete setup",
"complete",
"completed",
"completely confidential",
"compounded",
"comprehensive support",
"comprehensive training",
"comprehensive",
"compromise",
"concept",
"confident",
"confidential",
"congratulations",
"continued support",
"control",
"convenient",
"cost effective",
"courage",
"crammed",
"crammed",
"crucial",
"crucial",
"customize",
"cutting price",
"danger",
"dare you",
"debt free",
"deductible",
"deep discount",
"delivered to your door",
"description",
"deserve",
"desire",
"destiny",
"detailed information",
"detailed",
"difference",
"difficult",
"direct to you",
"direct",
"discount",
"discover",
"doesn't have to be",
"don't be left behind",
"don't delay",
"don't miss out",
"don't miss the boat",
"double income",
"durability",
"dynamic",
"eager",
"ease of use",
"ease",
"easily",
"easy installation",
"easy operation",
"easy ordering",
"easy payments",
"economical",
"effective",
"efficient",
"effortless",
"effortlessly",
"elegant",
"eligible",
"eliminate",
"emerging growth",
"emerging",
"enchanted",
"endeavor",
"endorse",
"endurance",
"enduring",
"energy",
"enhanced",
"enhancing",
"enjoy",
"enjoyment",
"enormous potential",
"enormous",
"enriched",
"enterprising",
"entire",
"envied",
"envision",
"essential",
"estimated",
"ethical",
"everything supplied",
"exact",
"exceed",
"excellent offer",
"excellent quality",
"excellent service",
"excellent",
"exceptional",
"excitement",
"exciting details",
"exclusive",
"exclusive",
"exhilarated",
"expansive",
"experience",
"expert advice",
"expert",
"experts agree",
"experts agree",
"experts say",
"explained",
"exploding",
"express service",
"extensive",
"extra income",
"extra",
"extraordinary",
"extremely informative",
"eye-catching",
"fabulous",
"fact",
"famous",
"fantasy",
"fascinating",
"fascination",
"fast results",
"fast service",
"fast",
"faster service",
"fast-setup",
"favorable",
"features include",
"financial",
"find the answer to",
"finest quality",
"first place",
"first-class",
"flash",
"flattering",
"flexibility",
"flourishes",
"focus",
"forecast",
"forever",
"formula",
"fortunate",
"fortune",
"fraction of the cost",
"fraction of the price",
"free advice",
"free consultation",
"free coupon",
"free delivery",
"free demonstration",
"free details",
"free estimates",
"free ideas",
"free issue",
"free membership",
"free newsletter",
"free of charge",
"free sample",
"free trial offer",
"free with purchase",
"free written evaluation",
"free/no obligation",
"free",
"freedom",
"freely",
"free-no obligation",
"fresh start",
"fresh",
"full or part time",
"full range of",
"full size",
"full spectrum",
"full",
"full-featured",
"fully explained",
"fully",
"fun",
"fundamentals",
"fundamentals",
"funny",
"future",
"gaining on",
"genuine",
"genuinely",
"get ahead",
"get results fast",
"get results overnight",
"get results-order now",
"get something extra",
"get something extra",
"get the facts",
"giant",
"gift with purchase",
"gift",
"gifted",
"gigantic",
"give",
"global",
"golden",
"good judgement",
"good reasons",
"good",
"good-taste",
"good-tasting",
"gorgeous",
"grace",
"gratification",
"greatest",
"greatful",
"ground-floor offer",
"ground-floor opportunity",
"growth",
"guarantee",
"guaranteed lowest price",
"guaranteed to work",
"handsome",
"handy",
"happy",
"hard hitting",
"hard",
"hassle free",
"have fun",
"healing",
"healthy",
"hearty",
"heavy",
"help",
"helping people like you",
"high class",
"high growth",
"high impact",
"high priority",
"high- rolling",
"high speed",
"high volume",
"high",
"highest commission offered",
"highest rated",
"high-light",
"highly rated",
"highly recommended",
"high-tech",
"honor",
"hope",
"hot property",
"hottest",
"how to",
"huge demand",
"huge difference",
"huge",
"hundreds sold",
"hundreds sold",
"hungry",
"hurry offer ends soon",
"idea",
"if you decide",
"illustrated",
"imagination",
"imaginative",
"immediate response",
"immediately",
"important",
"improve your life",
"improve",
"improved version",
"improved",
"in a flash",
"in minutes",
"in seconds",
"incentive for buying",
"incentives",
"increase your earning power",
"increasingly",
"incredible benefits",
"incredibly easy to use",
"in-demand",
"independent",
"in-depth",
"inexpensive",
"inflation-beating",
"inform",
"informative",
"innovation",
"innovation",
"insane prices",
"insatiable",
"insightful",
"inspiration",
"inspiration",
"inspire",
"instant",
"instructive",
"intangible",
"intelligent",
"interactive",
"interest free",
"interesting",
"intriguing",
"introducing",
"introductory offer",
"introductory offer",
"introductory rates",
"invest",
"investment",
"ironclad guarantee",
"it sells its self",
"it will boggle your mind",
"its a breeze",
"its a must",
"its confidential",
"its that easy",
"just in time",
"knowledge",
"larger than life",
"largest selling",
"largest",
"last minute",
"lasting impression",
"lasting",
"late-breaking",
"latest technology",
"latest",
"launching",
"lavishly",
"leadership",
"leading name",
"leading",
"learn about",
"legal",
"legendary",
"legitimate",
"less hassle",
"liberal",
"liberated",
"life time guarantee",
"lifeblood",
"lifetime income",
"lifetime warranty",
"lifetime",
"like no other",
"limited",
"live your dream",
"live",
"lively",
"long term",
"longevity",
"loved",
"low price",
"low risk solution",
"low",
"lower price",
"lowest prices ever",
"lowest",
"loyalty",
"luxury",
"luxury",
"magic",
"magnetizing",
"mail today!",
"mainstream",
"major",
"makes a great gift",
"mammoth",
"mammoth",
"mania",
"many years experience",
"massive",
"master",
"masterpiece",
"maximum",
"measure up",
"mega",
"millions sold",
"millions",
"minimal investment",
"miracle",
"modern",
"modified",
"money making facts",
"money-saving",
"monumental",
"motivation",
"multiple revenue streams",
"nation wide",
"national",
"natural growth",
"natural",
"neat",
"necessary",
"new and improved",
"new niche",
"new vision",
"new",
"next frontier",
"no application fee",
"no doubt",
"no experience necessary",
"no experience needed",
"no experience needed",
"no hassle",
"no hype",
"no money down",
"no money required",
"no obligation",
"no obligation",
"no problem",
"no restriction",
"no risk",
"no-hassles refund",
"no-nonsense",
"nostalgic",
"not available in stores",
"noted",
"nothing better!",
"nothing else to buy",
"now available",
"now is the time!",
"obligation",
"obsession",
"of the year",
"offer ends ( )",
"offer limited to first ( ) callers",
"official",
"once in a lifetime opportunity",
"only $",
"open 24 hours a day",
"open 7 days a week",
"opportunities",
"option ",
"optional",
"order direct",
"order now!",
"order today",
"organized",
"original",
"original",
"out-of-sight",
"outstanding benefits",
"outstanding",
"over coming",
"overnight delivery",
"overwhelming",
"ownership",
"participation is limited",
"patented",
"pay only.....",
"perfect",
"performance",
"permanent",
"perpetual",
"personal fortune",
"personalized",
"perspective",
"phenomenal",
"pioneers",
"plus get...",
"poised",
"popularity",
"portable",
"portable",
"potent",
"potential",
"powerful",
"practical",
"precious",
"precision",
"premier",
"preserve",
"prevent",
"preview",
"price comparison",
"price includes shipping",
"priceless",
"prices below competitors",
"pride",
"prime-quality",
"principle",
"priority",
"private invitation",
"privileged",
"productivity",
"professional",
"profit generating",
"profit",
"profitable",
"profusely",
"promising",
"promotional",
"promptness",
"prosper",
"protection",
"proven track record",
"proven",
"provocative",
"purchasing power",
"qualified",
"quality",
"quality-minded",
"quick tips",
"quickly",
"rank at the top",
"rapid change",
"rare",
"rave reviews",
"read all about it",
"real",
"reality",
"realize your dream",
"reap the benefits",
"receive free",
"red hot",
"reduced rates",
"reduced",
"refundable",
"reliable",
"relief",
"remarkable",
"rent to own",
"requested",
"respected name",
"results overnight",
"return it and owe nothing",
"returnable",
"reveal",
"reviewing",
"revised",
"revisited",
"revolutionary",
"rewards",
"rich",
"right now.",
"risk free trial",
"risk nothing!",
"riveting",
"roaring",
"rocketed",
"royalties",
"rush delivery",
"safe to the environment",
"safe",
"sale",
"same day delivery",
"same day service",
"satisfaction guarantee",
"save hundreds",
"save money",
"save thousands",
"save time",
"save",
"savvy",
"scarce",
"secret",
"secrets revealed",
"security",
"see the savings",
"selected",
"send for free details",
"send no money now",
"send today",
"sensational",
"set your own hours",
"setting high standards",
"shape your tomorrow",
"sharp",
"sharply",
"short term lease",
"showcased",
"significant",
"simple step",
"simple to use",
"simplified",
"simply powerful",
"sincerely",
"sizable",
"sizzling",
"skilled",
"sky-rocketed",
"slashing prices",
"small investment",
"smart",
"soar",
"softer",
"solve",
"special bonus",
"special discounts",
"special",
"specialized",
"specializing in",
"speed delivery",
"speedy",
"spotlight",
"stable",
"stand out from the crowd",
"standard",
"stardom",
"start with nothing",
"startling",
"start-up",
"state of the art",
"stay competitive",
"step-by-step",
"stimulating",
"stop wasting time",
"strange",
"strong",
"sturdy",
"substantial savings",
"succeed",
"successful",
"sufficient",
"suitable",
"super sale",
"super",
"superb",
"superior living",
"superior",
"support",
"support",
"sure to fit your budget",
"sure-fire",
"surging",
"surprise bonus",
"surprise",
"swiftest",
"take action now!",
"take advantage of",
"take care of",
"taking over",
"tax benefits",
"tax deductible",
"tech",
"technical",
"technology",
"terrific",
"test drive",
"tested and approved",
"tested",
"tests prove",
"there's nothing like it!",
"thousands sold",
"thousands",
"time limited info",
"time saving",
"time tested",
"timely",
"times running out",
"tip of the ice burg",
"to assist you",
"toll free",
"top level",
"top name",
"top secret!",
"top",
"total",
"tough",
"traditional",
"travel discounts",
"tremendous",
"tried and true",
"trouble free",
"trusting",
"truth",
"try before you buy",
"try before you buy",
"two free bonuses",
"ultimate",
"ultra",
"unbeatable",
"unbelievable bargains",
"unbelievable",
"unconditional",
"under priced",
"understanding",
"unique offer",
"unique system",
"united",
"universal",
"unlimited",
"unlock",
"unparalleled",
"unsurpassed",
"untapped market",
"untold behind the scenes",
"unusual",
"updated",
"upgraded",
"uplifting",
"up-scale",
"useful",
"useful",
"utilize",
"valuable",
"value for the dollar",
"value",
"variety",
"versatility",
"very hot",
"vibrant",
"vision",
"warning",
"we need your help",
"we pay postage and handling",
"we pay shipping and handling",
"we really care",
"wealth",
"wealthy",
"while supplies last",
"wholesale price",
"wide range of..",
"wide variety",
"willpower",
"win",
"wisdom",
"without lifting a finger",
"wonderful",
"word-of-mouth",
"works in minutes",
"world's greatest",
"worldwide",
"year round",
"you can too",
"you owe it to yourself",
"you qualify",
"you select",
"young",
"your choice of...",
"your choice",
"youthful"
    };
}
